export const CHANGE_ENTRY_TEXT = 'CHANGE_ENTRY_TEXT';
export const CHANGE_ENTRY_PRICE = 'CHANGE_ENTRY_PRICE';
export const CLEAR_ACTIVE_ENTRY = 'CLEAR_ACTIVE_ENTRY';
export const ACTIVATION_ENTRY = 'ACTIVATION_ENTRY';

export const ADD_ENTRY = 'ADD_ENTRY';
export const EDIT_ENTRY = 'EDIT_ENTRY';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';

export const UPDATE_FILTER_VALUE = 'UPDATE_FILTER_VALUE';